{% set version = "1.5.5" %}
{% set sha256 = "18f33b9a084678ef691fa64b164eeca185f2da69a2e294f73ee6740280b46896" %}
{% set variant = "openblas" %}

package:
  name: cycamore
  version: {{ version }}

source:
  fn: cycamore-{{ version }}-{{ sha256 }}.tar.gz
  url: https://github.com/cyclus/cycamore/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win or osx or py<=27]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cyclus {{ version }}
  run:
    - python
    - cyclus {{ version }}

test:
  source_files:
    - tests

about:
  home: http://fuelcycle.org/
  license: BSD 3-clause
  license_file: LICENSE.rst
  summary: "The Cyclus additional modules repository."

extra:
  recipe-maintainers:
    - scopatz
    - gonuke
    - bam241
    - katyhuff
    - FlanFlanagan
    - stompsjo
